language: c
compiler:
  - gcc
before_install:
  - sudo pip install cpp-coveralls
install:
  - ./install-deps
script:
  - ./configure --enable-gcov
  - make check
  - make distcheck
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
